### ISSUE TITLE
需要什么前置条件吗

### ISSUE THREAD

**Issue by ninetwozreo** [W2Ning/Visor_Finance_Vul_Poc#1]
大佬，这个需要什么前置条件吗，比如之前就有deposit，我直接来合约用好像没拿到visor

**Comment by W2Ning** [comment]
不需要任何前置条件

**Comment by ninetwozreo** [comment]
> 不需要任何前置条件

部署后直接attack ，msg.sender就可以拿到visor吗，我试了下没拿到哎，fork的块有问题么，13849000
![image](https://user-images.githubusercontent.com/37244857/147408491-bab3102d-bfb3-4bfd-b879-31902d34be60.png)

**Comment by W2Ning** [comment]
是`vVISR`...
攻击者手动把`vVISR`换成了`VISR`
但是实验环境我就没必要做这一步了

**Comment by ninetwozreo** [comment]
> 

哦哦，币种地址找错了，我换币种再试试，多谢大佬回复！

**Comment by W2Ning** [comment]
0x3a84aD5d16aDBE566BAA6b3DafE39Db3D5E261E5
好的, 我把ISSUE关掉了
